### ISSUE TITLE
What is the license of the dataset?

### ISSUE THREAD

**Issue by dmlls** [aalok-sathe/wikifactcheck-english#2]
Hi @aalok-sathe.

First off, thank you and your colleagues for this great dataset. Also, sorry for not opening this issue at https://github.com/wikifactcheck-english/wikifactcheck-english. Unfortunately, issues have been disabled there.

I wanted to ask, what is the license of the dataset?

We are working on a paper that introduces a negation-focused dataset (see https://github.com/dmlls/cannot-dataset), and are planning to release it under [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/). Since our dataset contains samples from WikiFactCheck-English, we want to make sure we respect its license.

**Comment by aalok-sathe** [comment]
Hi @dmlls, 
Thanks for reaching out. Apologies, I don't know why issues were disabled. Just enabled them.
Additionally, we've added license information to the main repo now:
https://github.com/wikifactcheck-english/wikifactcheck-english/blob/master/LICENSE.md
